language: php
php:
  - 5.5

mysql:
  database: drupal
  username: root
  encoding: utf8

services:
  - memcached

addons:
  hosts:
    - travis.midcamp.dev

before_install:
 - export BASEDIR=${PWD}
 - composer self-update
 - ci/install_ci.sh
 - ci/install_tests.sh

install:
 - phpenv rehash

before_script:
 - phpenv config-add ci/php/memcache.ini
 - phpenv config-add ci/php/tweaks.ini
 - ci/install_drupal_mysql.sh

script:
  - cd $BASEDIR/tests && ./bin/behat -fprogress
  - cd $BASEDIR && ci/vendor/bin/phploc --names=*.php,*.module,*.install,*.inc docroot/sites/all/modules/custom
