language: php
php:
  - 5.5

mysql:
  database: drupal
  username: root
  encoding: utf8

services:
  - memcached

before_install:
 - export BASEDIR=${PWD}
 - composer self-update
 - ci/install_drush.sh
 - alias drush="$BASEDIR/ci/vendor/bin/drush"
 - ci/install_tests.sh
 - ci/install_drupal_mysql.sh

install:
 - phpenv rehash

script:
  - $BASEDIR/tests/vendor/bin/behat -fprogress
