<?php

/**
 * @file
 * Module for Panels awesome sauce.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function midcamp_ctools_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/content_types';
  }
  return NULL;
}

/**
 * Implements hook_views_api().
 */
function midcamp_ctools_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'midcamp_ctools') . '/views',
  );
}

/**
 * Implements hook_entity_info_alter().
 */
function midcamp_ctools_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['user_page_teaser'] = array(
    'label' => 'User page: teaser',
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_preprocess_node().
 */
function midcamp_ctools_preprocess_node(&$variables) {
  if ($variables['view_mode'] == 'user_page_teaser') {
    $variables['theme_hook_suggestions'][] = 'node__user_page_teaser';
  }
}
